// Code generated by "stringer -type=Platform"; DO NOT EDIT.

package users

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PlatformWeb-0]
	_ = x[PlatformAndroid-1]
	_ = x[PlatformiOS-2]
	_ = x[PlatformLinux-3]
	_ = x[PlatformMacOS-4]
	_ = x[PlatformUnknown-5]
	_ = x[PlatformWindows-6]
}

const _Platform_name = "PlatformWebPlatformAndroidPlatformiOSPlatformLinuxPlatformMacOSPlatformUnknownPlatformWindows"

var _Platform_index = [...]uint8{0, 11, 26, 37, 50, 63, 78, 93}

func (i Platform) String() string {
	if i < 0 || i >= Platform(len(_Platform_index)-1) {
		return "Platform(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Platform_name[_Platform_index[i]:_Platform_index[i+1]]
}
