// Code generated by "stringer -type=Op -trimprefix=Op"; DO NOT EDIT.

package fireditto

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OpGET-0]
	_ = x[OpEmbed-1]
}

const _Op_name = "GETEmbed"

var _Op_index = [...]uint8{0, 3, 8}

func (i Op) String() string {
	if i >= Op(len(_Op_index)-1) {
		return "Op(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Op_name[_Op_index[i]:_Op_index[i+1]]
}
