// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.819
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func TextStream() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div id=\"content\" class=\"stream-container\" data-signals=\"{_streamStatus: &#39;idle&#39;, _currentLine: 0, _totalLines: 5, _content: &#39;&#39;}\"><h1>Datastar Text Streaming Demo</h1><div data-show=\"$_streamStatus != &#39;idle&#39;\" class=\"progress-bar\"><div class=\"progress-text\">Line <span data-text=\"$_currentLine\"></span> of <span data-text=\"$_totalLines\"></span></div></div><button data-on-click=\"@get(&#39;/templates/v1/text-stream?repeat=true&#39;)\" data-indicator-_loading data-attr-disabled=\"$_loading\" class=\"stream-button\"><span data-show=\"$_streamStatus == &#39;idle&#39;\">Start Streaming</span> <span data-show=\"$_streamStatus == &#39;waiting&#39;\">Connecting...</span> <span data-show=\"$_streamStatus == &#39;streaming&#39;\">Streaming...</span> <span data-show=\"$_streamStatus == &#39;complete&#39;\">Stream Again</span></button><div id=\"stream-content\" class=\"stream-content\"><div data-show=\"$_streamStatus == &#39;idle&#39;\" class=\"initial-message\">Click the button below to start streaming</div><div data-show=\"$_streamStatus == &#39;waiting&#39;\" class=\"waiting-message\">Waiting for stream to start...</div><markdown-renderer data-attr-content=\"$_content\" data-show=\"$_streamStatus != &#39;idle&#39; &amp;&amp; $_streamStatus != &#39;waiting&#39;\"></markdown-renderer></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
