// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.819
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func TextStream() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"stream-container\"><h1>SSE Text Streaming Demo</h1><div id=\"initial-message\">Waiting for text updates...</div><div id=\"stream-content\" hx-ext=\"sse\" sse-connect=\"/templates/v1/text-stream/events\" sse-swap=\"text-update\" sse-close=\"close\" hx-swap=\"beforeend\" class=\"stream-content\"></div><style>\n\t\t\t.stream-container {\n\t\t\t\tpadding: 20px;\n\t\t\t}\n\t\t\t.stream-content {\n\t\t\t\tpadding: 20px;\n\t\t\t\tborder: 1px solid #ddd;\n\t\t\t\tborder-radius: 4px;\n\t\t\t\tmargin: 20px 0;\n\t\t\t\tmin-height: 100px;\n\t\t\t\tfont-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Helvetica, Arial, sans-serif;\n\t\t\t\tline-height: 1.6;\n\t\t\t}\n\t\t\t.stream-content h1, h2, h3 {\n\t\t\t\tmargin: 1em 0 0.5em;\n\t\t\t}\n\t\t\t.stream-content code {\n\t\t\t\tbackground-color: #f6f8fa;\n\t\t\t\tpadding: 0.2em 0.4em;\n\t\t\t\tborder-radius: 3px;\n\t\t\t\tfont-family: monospace;\n\t\t\t}\n\t\t\t.stream-content pre {\n\t\t\t\tbackground-color: #f6f8fa;\n\t\t\t\tpadding: 16px;\n\t\t\t\tborder-radius: 6px;\n\t\t\t\toverflow: auto;\n\t\t\t}\n\t\t\t.stream-content pre code {\n\t\t\t\tpadding: 0;\n\t\t\t\tmargin: 0;\n\t\t\t\tbackground-color: transparent;\n\t\t\t}\n\t\t\t.stream-content blockquote {\n\t\t\t\tborder-left: 4px solid #ddd;\n\t\t\t\tpadding-left: 16px;\n\t\t\t\tmargin-left: 0;\n\t\t\t\tcolor: #666;\n\t\t\t}\n\t\t\t.error {\n\t\t\t\tcolor: #ff4444;\n\t\t\t\tfont-style: italic;\n\t\t\t}\n\t\t</style></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
